services:
  - type: web
    name: internshala-scraper
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true 