services:
  - type: web
    name: internshala-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true
    plan: free
